### ISSUE TITLE
NumUniqueSeparators error when serialized to JSON

### ISSUE THREAD

**Issue by dvreed77** [alteryx/nlp_primitives#113]
Separators is a set which causes error when getting serialized to JSON

**Comment by gsheni** [comment]
Can we take out the set? I don't see a reason for having it

**Comment by gsheni** [comment]
@dvreed77 Can we take out the set? I don't see a reason for having it

**Comment by dvreed77** [comment]
We can probably remove it, but I think we need to include some new tests to make sure things get serialized properly

**Comment by gsheni** [comment]
Sounds good. Adding this for our next sprint.
