### ISSUE TITLE
Add NumberOfCapitalWords primitive

### ISSUE THREAD

**Issue by gsheni** [alteryx/nlp_primitives#135]
- Determine the number of capital words present

**Comment by sbadithe** [comment]
Does this refer to words that start with a capital letter or consist of all capital letters?

**Comment by gsheni** [comment]
Words that start with a capital letter

**Comment by sbadithe** [comment]
I looked a little deeper and I found the `TitleWordCount` primitive behaves in the following way: 

```
t = nlp_primitives.TitleWordCount() 
words = ["Hello HEllo"]
t(words) 
```
yields 2.0 as a result. In this case, as I understand it, this behavior would be the same as `NumberOfCapitalWords`.
