### ISSUE TITLE
Add NumberOfWordsInQuotes primitive

### ISSUE THREAD

**Issue by gsheni** [alteryx/nlp_primitives#136]
- Determine the number of words in single/double quotes

**Comment by sbadithe** [comment]
@gsheni @thehomebrewnerd 

I think the semantics for this primitive are interesting. Would this primitive match for the following sentence: 

"word word word" 

And return 3? 

Or, do we just want to match words immediately wrapped by quotes, like the following:

Word "word" 

And return 1. 

The first approach enables the user to ask more interesting questions, like "how many words of dialogue were spoken in this text?" However there are a number of edge cases to be careful of here.

**Comment by gsheni** [comment]
I would say the first approach is what I had in mind. 
Regarding the edge case, I agree with you, we do count it if its enclosed in single/double quotes.
