### ISSUE TITLE
Add Woodwork to core dependencies in setup.cfg

### ISSUE THREAD

**Issue by thehomebrewnerd** [alteryx/nlp_primitives#163]
Imports from Woodwork are used in several places in the codebase, but Woodwork is not listed as a requirement in `setup.cfg`, but instead we rely on the install of Woodwork as a dependency of Featuretools. Since we directly use Woodwork in the code, we should consider adding it as a core dependency.

**Comment by sbadithe** [comment]
Do we want to support a particular version of Woodwork? 

I went ahead and put 0.8.1 for now, because I saw that the featuretools version was >=1.5.0. When I checked out the featuretools 1.5.0 release commit, I saw that woodwork was >=0.8.1 in it's setup.py.
