### ISSUE TITLE
Add NumUniqueSeparators primitive

### ISSUE THREAD

**Issue by gsheni** [alteryx/nlp_primitives#78]
- We can add a primitive to determine how many unique separators there are in a NaturalLanguage column. Separators could be user defined but includes `.,!\?;\n`
- This primitive should take NaturalLanguage as a input
- There should be unit tests for this primitive

**Comment by gsheni** [comment]
One thing I would be curious is if we can vectorize this primitive.

**Comment by tuethan1999** [comment]
@gsheni is there a reason we want to vectorize?

["The vectorize function is provided primarily for convenience, not for performance. The implementation is essentially a for loop."](https://numpy.org/doc/stable/reference/generated/numpy.vectorize.html)

**Comment by gsheni** [comment]
By vectorize, I did not mean that numpy function.
There are certain situations where you can avoid doing things 1 row value at a time. You can vectorization an operation and apply the operation at once to all values. For example
```python
A = np.random.randn(1000)
B = np.zeros(1000)
def func(a):
    return a**2 + 5*a +35 
for i in range(1000):
    B[i] = func(A[i])
```
- You can vectorize that as:
```python
B = A**2 + 5*A +35
```
- For this primitive, let's see if there is a quick way of vectorization. If not, feel free to use a for loop (`apply`).

- Helpful links:
- https://medium.com/analytics-vidhya/improve-data-processing-speeds-while-using-numpy-arrays-in-python-through-vectorization-49ea6cc9004e
- https://blog.paperspace.com/numpy-optimization-vectorization-and-broadcasting/
